dependencies:
  # Cropbox.jl
  - sympy
  # Python
  #- python=3.8
  - numpy
  - scipy
  - pandas
  - matplotlib
  - seaborn
  # R
  - r-base>=4
  - r-irkernel>=1.1
  - r-tidyverse
  # JupyterHub
  - jupyterhub=1.1.0
  - nbgitpuller
  - jupytext
