channels:
  - tomyun
  - conda-forge
  - defaults
dependencies:
  # Cropbox.jl
  - sympy
  # Python
  - python=3.8
  - numpy
  - scipy
  - pandas
  - matplotlib
  - seaborn
  - tensorflow>=2.0
  # R
  - r-base>=4
  - r-irkernel>=1.1
  - r-tidyverse
  - r-tensorflow
  - r-keras
  - r-tfdatasets
  - r-randomforest
  - r-hydrogof
  # JupyterHub
  - jupyterhub
  - nbgitpuller
  - jupytext
  # override repo2docker environment.yml
  - ipywidgets=7.5.*
  - jupyterlab=2.2.*
  - jupyterhub-singleuser=1.1.*
  - nbconvert=5.6.*
  - nbresuse=0.3.*
  - notebook=6.0.*
  - nteract_on_jupyter=2.1.*
  # reinstall jupyter_offlinenotebook for custom python environment
  # https://github.com/jupyterhub/repo2docker/issues/961
  - pip
  - pip:
    - jupyter-offlinenotebook==0.1.0
