channels:
  - tomyun
  - conda-forge
  - defaults
dependencies:
  # Cropbox.jl
  - sympy
  # Python
  #- python=3.8
  - numpy
  - scipy
  - pandas
  - matplotlib
  - seaborn
  - tensorflow>=2.0
  # R
  - r-base>=4
  - r-irkernel>=1.1
  - r-tidyverse
  - r-tensorflow
  - r-keras
  - r-tfdatasets
  - r-randomforest
  - r-hydrogof
  # JupyterHub
  - jupyterhub
  - nbgitpuller
  - jupytext
