name: Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: easimon/maximize-build-space@master
        with:
          remove-dotnet: 'true'
          remove-android: 'true'
      - uses: actions/checkout@v2
      - uses: jupyterhub/repo2docker-action@master
        with:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          REPO_DIR: "/home/Cropbox.jl"
          IMAGE_NAME: "tomyun/cropbox"
          LATEST_TAG_OFF: true
          MYBINDERORG_TAG: ${{ github.event.ref }}
